import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import './global.css'
export const metadata = {
  title: 'کارباکار',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body>
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
