import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import './global.css'
export const metadata = {
  title: 'کارباکار',
  description: 'Generated by create next app',
}
import { ThemeProvider } from '@mui/material';
import theme from '../src/theme';

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
